mysql:
  enabled: true
  user: root
  password: wVKACGjtoyWYYkIc
  address: 95.216.155.199

enderpearl-cooldown: 16

vault-sizes:
  1: 9
  2: 27
  3: 54

chest-protect:
  default: 20

spawn:
  x: 0
  y: 64
  z: 0
  yaw: '0.0'
  pitch: '0.0'
  world: 'world'

effects:
  teleport:
    enabled: true
    sound: 'ENTITY_ENDERMAN_TELEPORT'
  quit:
    enabled: true

other:
  links:
    discord: 'http://autiomc.eu/discord'
    web-full: 'http://www.autiomc.eu'
    web: 'www.autiomc.eu'
    store: 'http://autiomc.eu/kauppa'
  logging: true

chat:
  prefixes:
    default: '&2&lSorsaMC &7»'
    error: '&2&lVirhe &7»'
    afk: '&2&lAFK &7»'
    debug: '&2&lVirheenkorjaus &7»'
  format: '%rank%%name%: &f%message%'

messages:
  join: '&7[&a+&7] %player%'
  leave: '&7[&c-&7] %player%'

random-tp:
  range: 5000
  cooldown-in-minutes: 3

auto-broadcaster:
  messages:
    - '&7Lorem ipsum dolor sit amet'
  interval-in-minutes: 1

