name: SorsaSurvival
version: 0.8
main: me.tr.survival.main.Main
description: SorsaMC survival plugin
api-version: 1.13
depend: [UltimateTimber, LuckPerms, ProtocolLib, PlayerParticles, Vault, NametagEdit, WorldGuard]

commands:
  bal:
    description: Balance
    aliases: [balance, raha, money]
  pay:
    description: Maksa
    aliases: [maksa]
  save:
    description: Tallenna
    aliases: [tallenna]
  profile:
    description: Statistiikat
    aliases: [stats, tiedot, profiili]
  home:
    description: Koti
    aliases: [koti, homes, delhome]
  #arvo:
   # description: Arvojen hallinta
    #aliases: [rank]
  spawn:
    description: Vie Spawnille
  setspawn:
    description: Aseta Spawn
  #level:
   # description: Hallinnoi Leveleitä
   # aliases: [lvl]
  ping:
    description: Viive
    aliases: [viive]
  speed:
    description: Lentonopeus
  settings:
    description: Asetukset
    aliases: [asetukset]
  gamemode:
    description: Pelimuoto
    aliases: [gm]
  #msg:
   # description: Yksityisviestit
    #aliases: [tell, whisper, viesti]
  #r:
    #description: Vastaa viestiin
    #aliases: [vastaa]
  sethome:
    description: Aseta koti
  heal:
    description: Paranna pelaaja
  time:
    description: Hallitse pelin aikaa
    aliases: [aika]
  fly:
    description: Lento
    aliases: [lento]
  enchant:
    description: Lumoa itemi
    aliases: [lumoa, lumous]
  crystal:
    description: Kristallit
    aliases: [crystals, kristallit]
  rtp:
    description: RTP
  autio:
    description: Autio
    aliases: [sorsa, sorsamc]
  skull:
    description: Pelaajan kallo
  debug:
    description: Virheenkorjaus
  posti:
    description: Posti
    aliases: [mail, kirje]
  arpa:
    description: Arvat
    aliases: [lotto, lottery]
  iteminfo:
    description: Blockin id
    aliases: [id]
  warp:
    description: Warpit
    aliases: [warps]
  tehostus:
    description: Tehostukset
    aliases: [booster, boosters, tehostukset]
  back:
    description: Viimeisein sijainti
    aliases: [takaisin]
  enderchest:
    description: Avaa enderchest
    aliases: [ec]
  tpa:
    description: Tpa-pyynto
  tpaccept:
    description: Vahvista tpa-pyynto
    aliases: [tpyes]
  tpahere:
    description: Tpa-pyynto sinun luoksesi
  tp:
    description: Teleporttaa pelaajaan
    aliases: [teleport]
  tphere:
    description: Teleporttaa pelaaja luoksesi
  tpdeny:
    description: Kiella tpa-pyynto
    aliases: [tpno]
  weather:
    description: Sää
    aliases: [sää]
  staff:
    description: Ylläpito-paneeli
    aliases: [yp, ylläpito, admin, mod]
  apua:
    description: Apua
    aliases: [help, commands, komennot, faq]
  koordinaatit:
    description: Katso sijaintisi
    aliases: [here, loc, location]
  world:
    description: Maailmat
    aliases: [worlds, maailma, maailmat]
  broadcast:
    description: Ilmoita
    aliases: [bc, ilmoita, shout]
  discord:
    description: Discord-yhteisö
    aliases: [dc]
  vanish:
    description: Piiloudu
    aliases: [v, piiloudu]
  trade:
    description: Vaihtokauppa
    aliases: [vaihto, vaihda]
  baltop:
    description: Top raha
    aliases: [rahatop, btop]
  clear:
    description: Clear inventory
    aliases: [invclear, clearinventory]
  matkusta:
    description: Matkustaminen
    aliases: [travel, matkustaminen]
  valuutta:
    description: Valuutta-asiat
  shekki:
    description: Kirjoita shekkejä
  stop:
    description: Stop the server
    aliases: [shutdown, restart]
  forcestop:
    description: Force Stop
    aliases: [forcerestart, forceshutdown]
  reppu:
    description: Talleta tavaroita turvallisesti
    aliases: [backpack, vault]
  invsee:
    description: Tarkastele inventorya
  kosmetiikka:
    description: Kosmetiikka
    aliases: [cosmetics, particles, partikkelit, nuolijanat, arrowtrail]
  givevip:
    description: Give Vip command
  hehku:
    description: Hehkuefektit
    aliases: [glow, hehkuefektit]
  vip:
    description: Vip-ominaisuudet
    aliases: [vipsettings]
  houkutin:
    description: Spawnin houkutin
  uptime:
    description: Uptime
  ääri:
    description: End-maailma
    aliases: [loppu]