name: AutioMC
version: 0.8
main: me.tr.survival.main.Main
description: Survival for AutioMC
api-version: 1.13
depend: [UltimateTimber]

commands:
  bal:
    description: Balance
    aliases: [balance, raha, rahatilanne, money]
  save:
    description: Tallenna
    aliases: [tallenna]
  profile:
    description: Statistiikat
    aliases: [stats, tilastot, tiedot]
  home:
    description: Koti
    aliases: [koti, homes, delhome]
  arvo:
    description: Arvojen hallinta
    aliases: [rank]
  spawn:
    description: Vie Spawnille
  setspawn:
    description: Aseta Spawn
  level:
    description: Hallinnoi Leveleitä
    aliases: [lvl]
  ping:
    description: Viive
    aliases: [viive]
  speed:
    description: Lentonopeus
  settings:
    description: Asetukset
    aliases: [asetukset]
  gamemode:
    description: Pelimuoto
    aliases: [gm]
  msg:
    description: Yksityisviestit
    aliases: [tell, whisper, viesti]
  r:
    description: Vastaa viestiin
    aliases: [vastaa]
  sethome:
    description: Aseta koti
  heal:
    description: Paranna pelaaja
  time:
    description: Hallitse pelin aikaa
    aliases: [aika]
  fly:
    description: Lento
    aliases: [lento]
  enchant:
    description: Lumoa itemi
    aliases: [lumoa, lumous]
  crystal:
    description: Kristallit
    aliases: [crystals, kristallit]
  rtp:
    description: RTP
  autio:
    description: Autio
  seen:
    description: Pelaajan vanhat osoitteet
    aliases: [history]
  disguise:
    description: Vaihda skiniä
    aliases: [piiloudu]
  skull:
    description: Pelaajan kallo
  debug:
    description: Virheenkorjaus
  admin:
    description: Admin-toimintoja
  posti:
    description: Posti
    aliases: [mail, kirje]
  arpa:
    description: Arvat
    aliases: [lotto, lottery]
  iteminfo:
    description: Blockin id
    aliases: [id]
  warp:
    description: Warpit
    aliases: [warps]
  tehostus:
    description: Tehostukset
    aliases: [booster, boosters, tehostukset]
  back:
    description: Viimeisein sijainti
    aliases: [takaisin]